### ISSUE TITLE
Link not generating

### ISSUE THREAD

**Issue by Sirius-Black4** [LiNuX-Mallu/CAM-DUMPER#11]
![image](https://user-images.githubusercontent.com/70875712/107193075-703f0300-6a14-11eb-96ea-469c86bf1097.png)

**Comment by johnitto** [comment]
Same problem

**Comment by aboodisking507** [comment]
Same problem

**Comment by HACKE-RC** [comment]
Starr ngrok before you start the tool

**Comment by LiNuX-Mallu** [comment]
Turn on hotspot in android 
Others should install suitable ngrok version manually .
