### ISSUE TITLE
Didn't get the photo

### ISSUE THREAD

**Issue by JoshuaSQL** [LiNuX-Mallu/CAM-DUMPER#13]
I didnt't get the photo after they clicked on the link. Only IP showed up

**Comment by GEFORX** [comment]
if the target click on the link but don't allow camera using ....ooops....
but if yes you will see camefile or some numbers....and use  cat " number
JPg " and the pic will appear .....

**Comment by JoshuaSQL** [comment]
Ok got it!
I will close the case
