### ISSUE TITLE
link not genarating

### ISSUE THREAD

**Issue by IvoniousChuck** [LiNuX-Mallu/CAM-DUMPER#15]

**Comment by LiNuX-Mallu** [comment]
Post screenshot and your os details .

**Comment by LiNuX-Mallu** [comment]
> 
> 
> Link not generating

any other details ?

**Comment by LiNuX-Mallu** [comment]
https://github.com/LiNuX-Mallu/CAM-DUMPER/issues/17#issuecomment-913815129

Read this
