### ISSUE TITLE
The link doesnt generate

### ISSUE THREAD

**Issue by Reaperv2** [LiNuX-Mallu/CAM-DUMPER#16]
Its just blank there is no link ive tried to turn on hotspot but still doesnt work please help
![Screenshot_2021-08-31-13-16-04-805_com termux](https://user-images.githubusercontent.com/89647419/131485424-e9df3a6c-d0f7-46e1-b9cb-a3d8953c7341.jpg)

And this with hotspot on 
![Screenshot_2021-08-31-13-19-08-057_com termux](https://user-images.githubusercontent.com/89647419/131485867-231815fd-a07e-4c01-9215-7b059929bd68.jpg)

**Comment by LiNuX-Mallu** [comment]
did you download ngrok ?

**Comment by bennetho** [comment]
Yes but link doesn’t generate

**Comment by LiNuX-Mallu** [comment]
https://github.com/LiNuX-Mallu/CAM-DUMPER/issues/17#issuecomment-913815129

**Comment by bennetho** [comment]
does not work

**Comment by LiNuX-Mallu** [comment]
> does not work

Delete the tool and reinstall it by cloning then try .

**Comment by LiNuX-Mallu** [comment]
Also take a look at new installation instructions .
