### ISSUE TITLE
Other tools not working 

### ISSUE THREAD

**Issue by Devprajapati2003** [LiNuX-Mallu/CAM-DUMPER#18]
Your tool is perfectly  working  but other tools which generate ngrok links  like  zphisher , shark , sayhello etc are not generating.  I tried the same thing which you used in your tool still it doesn't work .

So can you tell what is the problem behind these tools ??

**Comment by LiNuX-Mallu** [comment]
https://github.com/LiNuX-Mallu/CAM-DUMPER/issues/17#issuecomment-913815129

This trick will work .

**Comment by Devprajapati2003** [comment]
> [#17 (comment)](https://github.com/LiNuX-Mallu/CAM-DUMPER/issues/17#issuecomment-913815129)
> 
> This trick will work .

No not working.  When i type of first command of this process it says unable to locate tq

**Comment by Devprajapati2003** [comment]
> [#17 (comment)](https://github.com/LiNuX-Mallu/CAM-DUMPER/issues/17#issuecomment-913815129)
> 
> This trick will work .

I got it bro .
You have written a little bit wrong word . 

> [#17 (comment)](https://github.com/LiNuX-Mallu/CAM-DUMPER/issues/17#issuecomment-913815129)
> 
> This trick will work .


I got it bro but  i think you have written first command wrong 
It is apt install jq curl  anr you have written   apt install tq curl .

But i tried it and thankfully Link came but same  problem.  The Link is working only on our phone not on victim phone

**Comment by Devprajapati2003** [comment]
It appears like Tunnel ngrok not found on victim phone

**Comment by LiNuX-Mallu** [comment]
> 
> 
> It appears like Tunnel ngrok not found on victim phone

you sure you have stable internet connection
also try adding authtoken

(i ve fixed the spell mistake thank you)
