### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by almera-vs** [LiNuX-Mallu/CAM-DUMPER#19]
I'm getting "null" whenever i use the trick you mentioned in issue #17. I tried to use the curl command (2nd pic) after executing the script (1st pic) and there's no url. 

Also I'm not sure if it's important, but in "captured_files > new" there's null as well.

![Screenshot_2021-09-14-21-31-16-093_com.termux.jpg](https://user-images.githubusercontent.com/60035016/133323538-4e9b66db-3c33-4b73-abed-82d52fcc7b63.jpg)

![Screenshot_2021-09-14-21-43-51-420_com.termux.jpg](https://user-images.githubusercontent.com/60035016/133323541-16a7fee1-a2d5-4524-9f65-0509e018e0e0.jpg)

**Comment by Devprajapati2003** [comment]
https://www.devprajapati27.me/2021/09/1-termux-setup-storage-2-apt-update-3.html?m=1


Use the commands given on the above website.  It will work 110 % .

**Comment by almera-vs** [comment]
> https://www.devprajapati27.me/2021/09/1-termux-setup-storage-2-apt-update-3.html?m=1
> 
> 
> Use the commands given on the above website.  It will work 110 % .

Didn't work 😔

**Comment by Devprajapati2003** [comment]
> > https://www.devprajapati27.me/2021/09/1-termux-setup-storage-2-apt-update-3.html?m=1
> > Use the commands given on the above website.  It will work 110 % .
> 
> Didn't work 😔

No bro it is working.  I have a youtube and telegram channel where my subscribers also thanked me as tool is perfectly working  

https://www.instagram.com/dev_prajapati_27/
This is my insta id . You can ask me where you are stuck 

And my telegram channel  https://t.me/dev_prajapati_27

**Comment by LiNuX-Mallu** [comment]
> 
> 
> > > https://www.devprajapati27.me/2021/09/1-termux-setup-storage-2-apt-update-3.html?m=1
> > > Use the commands given on the above website.  It will work 110 % .
> > 
> > 
> > Didn't work 😔
> 
> No bro it is working. I have a youtube and telegram channel where my subscribers also thanked me as tool is perfectly working
> 
> https://www.instagram.com/dev_prajapati_27/
> This is my insta id . You can ask me where you are stuck
> 
> And my telegram channel https://t.me/dev_prajapati_27

please delete the tool and re clone it 
also run $ rm -rf $HOME/.ngrok
you dont have to install ngrok seperately and dont have to do anything else 
just make sure you have turned on your hotspot

**Comment by LiNuX-Mallu** [comment]
> 
> 
> > https://www.devprajapati27.me/2021/09/1-termux-setup-storage-2-apt-update-3.html?m=1
> > Use the commands given on the above website.  It will work 110 % .
> 
> Didn't work 😔

please delete the tool and re clone it
also run $ rm $HOME/.ngrok2/ngrok.yml
you dont have to install ngrok seperately and dont have to do anything else
just make sure you have turned on your hotspot

**Comment by LiNuX-Mallu** [comment]
> 
> 
> > https://www.devprajapati27.me/2021/09/1-termux-setup-storage-2-apt-update-3.html?m=1
> > Use the commands given on the above website.  It will work 110 % .
> 
> Didn't work 😔

do me a favor
run     $  cat $HOME/.ngrok2/ngrok.yml
then take a screenshot of what you see & send it

**Comment by LiNuX-Mallu** [comment]
> 
> 
> I'm getting "null" whenever i use the trick you mentioned in issue #17. I tried to use the curl command (2nd pic) after executing the script (1st pic) and there's no url.
> 
> Also I'm not sure if it's important, but in "captured_files > new" there's null as well.
> 
> ![Screenshot_2021-09-14-21-31-16-093_com.termux.jpg](https://user-images.githubusercontent.com/60035016/133323538-4e9b66db-3c33-4b73-abed-82d52fcc7b63.jpg)
> 
> ![Screenshot_2021-09-14-21-43-51-420_com.termux.jpg](https://user-images.githubusercontent.com/60035016/133323541-16a7fee1-a2d5-4524-9f65-0509e018e0e0.jpg)

i can see that you are using wifi , that mean you cant turn on hotspot , you need to turn on hotspot .

**Comment by almera-vs** [comment]
> i can see that you are using wifi , that mean you cant turn on hotspot , you need to turn on hotspot .

But when I turn on the hotspot I don't have the wifi... What now? I can't use mobile data.

**Comment by LiNuX-Mallu** [comment]
> 
> 
> > i can see that you are using wifi , that mean you cant turn on hotspot , you need to turn on hotspot .
> 
> But when I turn on the hotspot I don't have the wifi... What now? I can't use mobile data.

hotspot is must anyway so you have to find other way to get internet

there were a ngrok old version which doesnt need hotspot but i couldnt find it source .
 
try bluetooth tethering method if you have 2 android
