### ISSUE TITLE
Why the link is not opening it shows Tunnel 76e3-110-224-255-170.ngrok.io not foundERR_NGROK_3200

### ISSUE THREAD

**Issue by loneumar** [LiNuX-Mallu/CAM-DUMPER#21]
Why the link is not opening it shows Tunnel 76e3-110-224-255-170.ngrok.io not foundERR_NGROK_3200

**Comment by LiNuX-Mallu** [comment]
Did you try after restarting termux ?

**Comment by loneumar** [comment]
Noo

**Comment by LiNuX-Mallu** [comment]
Adding authtoken can fix lot of problems occurred from tunneling .

Go to ngrok.com
Then sign up and copy authtoken
Then run
./ngrok authtoken <your token>
In cam-dumper directory
