### ISSUE TITLE
link not direct

### ISSUE THREAD

**Issue by lenovix** [LiNuX-Mallu/CAM-DUMPER#3]
![Screenshot from 2020-07-08 11-37-45](https://user-images.githubusercontent.com/42912095/86877359-ec850700-c110-11ea-821d-b90a66f4b8c6.png)

**Comment by LiNuXM4IIU** [comment]
elaborate

**Comment by Sirius-Black4** [comment]
same problem

**Comment by johnitto** [comment]
I have the same problem how can I solve it

**Comment by LiNuX-Mallu** [comment]
Install suitable ngrok for your system
And put it in the path CAM-DUMPER/

**Comment by Drisswrld** [comment]
How?

**Comment by Drisswrld** [comment]
I tried more than one tool i face the same problem anyone can help to fix this please?

**Comment by LiNuX-Mallu** [comment]
> I tried more than one tool i face the same problem anyone can help to fix this please?

I fixed everything just today and i guess everything is okay so you should check and let me know
Also follow The new instructions that added in the README .
Thank you

**Comment by Absenskq** [comment]
I have this problem now
