### ISSUE TITLE
Error help

### ISSUE THREAD

**Issue by strazzzy** [LiNuX-Mallu/CAM-DUMPER#47]
[+] Starting Serveo... candumper.sh: line 127: which: command not found camdumper.sh: line 127: -c: command not found [+] Starting php server... (localhost:3333) grep: sendlink: No such file or directory [+] Direct link: grep: sendlink: No such file or directory.   Help please
![Screenshot_2023-09-18-09-19-34-071_com termux](https://github.com/LiNuX-Mallu/CAM-DUMPER/assets/145314210/295ea14c-2b50-44ea-b028-2a2d043e87d1)

**Comment by LiNuX-Mallu** [comment]
Serveo won't work, tdy
